POST http://127.0.0.1:8080/events
Content-Type: application/json

{
    "name": "test event 2",
    "description": "A test description with dummy text 2",
    "location": "Location somewhere",
    "datetime": "2024-01-01T15:30:00.000Z"
}
