PUT http://127.0.0.1:8080/events/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQHRlc3QuY28iLCJleHAiOjE3MTIwMzA5OTYsInVzZXJJZCI6Mn0.vyW1vEcm8ghQ7bSlbtve6nBTh8ZAQJe93ma2Ci1yrBU

{
    "name": "Test event updated 77777 !!!",
    "description": "Test description with dummy text Updated222",
    "location": "Location somewhere updated 22!!!",
    "datetime": "2024-01-01T15:30:00.000Z"
}